---
title: Omar Fouad
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    permalink: "/blog/:title/"
  uploads:
    title: Uploads
    output: true
email: me@omarfouad.com
description: omar Fouad is a designer/software engineer based in Rome, Italy.
baseurl: "/"
url: http://omarfouad.com
twitter: omarfouad
color: "#bdbdbd"
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
