
title: Omar Fouad
email: me@omarfouad.com
description: > 
  omar Fouad is a designer/software engineer based in Rome, Italy.
baseurl: "/" 
url: "http://omarfouad.com" 
twitter: omarfouad
homecolor: '#4CA4F1'

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
